In [1]:
pip install hazm

Requirement already satisfied: hazm in /usr/local/lib/python3.10/dist-packages (0.10.0)
Requirement already satisfied: fasttext-wheel<0.10.0,>=0.9.2 in /usr/local/lib/python3.10/dist-packages (from hazm) (0.9.2)
Requirement already satisfied: flashtext<3.0,>=2.7 in /usr/local/lib/python3.10/dist-packages (from hazm) (2.7)
Requirement already satisfied: gensim<5.0.0,>=4.3.1 in /usr/local/lib/python3.10/dist-packages (from hazm) (4.3.3)
Requirement already satisfied: nltk<4.0.0,>=3.8.1 in /usr/local/lib/python3.10/dist-packages (from hazm) (3.9.1)
Requirement already satisfied: numpy==1.24.3 in /usr/local/lib/python3.10/dist-packages (from hazm) (1.24.3)
Requirement already satisfied: python-crfsuite<0.10.0,>=0.9.9 in /usr/local/lib/python3.10/dist-packages (from hazm) (0.9.11)
Requirement already satisfied: scikit-learn<2.0.0,>=1.2.2 in /usr/local/lib/python3.10/dist-packages (from hazm) (1.5.2)
Requirement already satisfied: pybind11>=2.2 in /usr/local/lib/python3.10/dist-packages (from fasttext-wheel<0.10.0,>=0.9.2->hazm) (2.13.6)
Requirement already satisfied: setuptools>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from fasttext-wheel<0.10.0,>=0.9.2->hazm) (75.1.0)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from gensim<5.0.0,>=4.3.1->hazm) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.10/dist-packages (from gensim<5.0.0,>=4.3.1->hazm) (7.0.5)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk<4.0.0,>=3.8.1->hazm) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk<4.0.0,>=3.8.1->hazm) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk<4.0.0,>=3.8.1->hazm) (2024.9.11)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk<4.0.0,>=3.8.1->hazm) (4.66.6)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2.0.0,>=1.2.2->hazm) (3.5.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.10/dist-packages (from smart-open>=1.8.1->gensim<5.0.0,>=4.3.1->hazm) (1.17.0)

In [25]:
import numpy as np
import pandas as pd
import re
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from hazm import *
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import f1_score

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [28]:
data = pd.read_csv('/content/drive/My Drive/Colab Notebooks/ML/11.project2/text_categorization/data/yektanet_train.csv')
data

,category,description,text_content,title,h1,h2,url,domain,id
0,کتاب و ادبیات,"از شوبنده ها: جستجو معنی ""از شوبنده ها"" در فره...",معنی از شوبنده ها | جدول یاب از شوبنده ها 381,معنی از شوبنده ها | جدول یاب,معنی از شوبنده ها,از شوبنده ها در معادل ابجد,jadvalyab.ir/search?q=%D8%A7%D8%B2+%D8%B4%D9%8...,jadvalyab.ir,158
1,تجارت و اقتصاد,بیت‌کوین کش یک ارز مجازی مشهور است و بیت‌کوین ...,عکس بیت‌کوین کش برای پروفایل عکس و والپیپرهای ...,عکس بیت‌کوین کش برای پروفایل,عکس بیت‌کوین کش برای پروفایل,عکس بیت کوین با کیفیت 4K عکس ارزهای دیجیتال عک...,jowhareh.com/photo/%D8%B9%DA%A9%D8%B3-%D8%A8%D...,jowhareh.com,3268
2,سلامت,نوبت دهی دکتر مهناز عابدینی متخصص رادیولوژی و ...,دکتر مهناز عابدینی متخصص رادیولوژی و سونوگرافی...,دکتر مهناز عابدینی متخصص رادیولوژی و سونوگرافی...,دکتر مهناز عابدینی,آدرس و تلفن دکتر مهناز عابدینی نظرات و تجربیات...,doctor-yab.ir/Search/14773/%D8%AF%DA%A9%D8%AA%...,doctor-yab.ir,175
3,تکنولوژی و کامپبوتر,نرم افزار Geph برای اندروید یک پلت‌فرم چندسکوی...,دانلود تحریم‌گذر Geph برای اندروید خانه/اندروی...,دانلود تحریم‌گذر Geph برای اندروید,دانلود تحریم‌گذر Geph برای اندروید,دانلود نرم افزار Geph,palexe.site/dl/geph-android/,palexe.site,3402
4,تکنولوژی و کامپبوتر,سری جدید تلویزیون‌های هوشمند سامسونگ که با نام...,ترفندهای پرکاربرد تلویزیون‌‌های هوشمند سامسونگ...,ترفندهای پرکاربرد تلویزیون‌‌های هوشمند سامسونگ...,ترفندهای پرکاربرد تلویزیون‌‌های هوشمند سامسونگ,راه‌اندازی تلویزیون همگام‌سازی کنترل اتصال به ...,rokhdadeghtesadi.ir/43874/,rokhdadeghtesadi.ir,3811
...,...,...,...,...,...,...,...,...,...
4784,سلامت,سلام خانم دکتر یه سوال مهم دارم آیا قرص ال دی ...,قرص ال دی با دوفاستون تداخل داره؟ پرسش (1397/0...,قرص ال دی با دوفاستون تداخل داره؟,قرص ال دی با دوفاستون تداخل داره؟,NaN,ooma.org/ask/77389/%D9%82%D8%B1%D8%B5-%D8%A7%D...,ooma.org,769
4785,خانه و باغبانی,فروش نقدی و اقساطی ماشین لباسشویی اسنوا سری ها...,فروش نقدی و اقساطی ماشین لباسشویی اسنوا سری ها...,فروش نقدی و اقساطی ماشین لباسشویی اسنوا سری ها...,فروش اقساطی ماشین لباسشویی اسنوا سری هارمونی 8...,فروش اقساطی کالای دیجیتال فروش اقساطی لوازم اد...,ghesticlub.com/Products/Snowa-Harmony-8-kg-was...,ghesticlub.com,1226
4786,غذا و نوشیدنی,قهوه سرا در مشهد -شماره تلفن قهوه سرا در مشهد ...,قهوه درویش در مشهد - پشت بام تهران ورود/ثبت نا...,قهوه درویش در مشهد - پشت بام,قهوه درویش در مشهد,قهوه درویش در مشهد,poshtebam.com/Banners/AdsDetail/377919/,poshtebam.com,2967
4787,ورزش,گزارش برخی رسانه‌های خارجی نشان می‌دهد اطلاعات...,کمک غیرمستقیم فیفا به کی‌روش! | تمام رقیبان تی...,کمک غیرمستقیم فیفا به کی‌روش! | تمام رقیبان تی...,کمک غیرمستقیم فیفا به کی‌روش! | تمام رقیبان تی...,Hamshahri Online برچسب‌ها پر بیننده‌ترین اخبار...,hamshahrionline.ir/news/715355/%DA%A9%D9%85%DA...,hamshahrionline.ir,2684
4788,تکنولوژی و کامپبوتر,دانلود برنامه جدید برای به روزرسانی درایورهای ...,دانلود Driver DR 6.3.0.42950 – نرم افزار به رو...,دانلود Driver DR 6.3.0.42950 – نرم افزار به رو...,دانلود رایگان نرم افزار دانلود Driver DR 6.3.0...,تبلیغات تبلیغات تبلیغات تبلیغات دانلود Driver DR,downloadsoftware.ir/driver-dr.php/,downloadsoftware.ir,4354

In [29]:
# splitting the dataset
train, test = train_test_split(data, test_size = 0.2)

In [30]:
# applyingoversampler = RandomOverSampler()
oversampler = RandomOverSampler()
X_train, y_train = oversampler.fit_resample(train, train['category'])

In [31]:
X_train

,category,description,text_content,title,h1,h2,url,domain,id
0,سفر و گردشگری,معرفی جاهای دیدنی اسپانیا | طبیعت اسپانیا | شه...,معرفی 40 تا از بهترین جاهای دیدنی اسپانیا | کب...,معرفی 40 تا از بهترین جاهای دیدنی اسپانیا | کب...,معرفی 40 تا از بهترین جاهای دیدنی اسپانیا,1- کلیسای ساگرادا فامیلیا (Sagrada Familia) 2-...,kababoketab.ir/blog/introducing-40-of-the-best...,kababoketab.ir,1883
1,غذا و نوشیدنی,کباب برگ را نباید هیچ وقت لای نان قرار داد زیر...,کباب برگ - چی بپزم دسته بندي پلو کباب املت...,کباب برگ - چی بپزم,دسته بندي جست و جو تبلیغات دوستان غذاهاي پربين...,13 نظر برای کباب برگ نظرت چیه؟,chibepazam.ir/%DA%A9%D8%A8%D8%A7%D8%A8-%D8%A8%...,chibepazam.ir,381
2,موسیقی,دانلود آهنگ یونس بخرد به نام مه کافرین/ جدیدتر...,دانلود آهنگ یونس بخرد به نام مه کافرین دانلود ...,دانلود آهنگ یونس بخرد به نام مه کافرین,دانلود آهنگ جدید ، محلی ، دیس لاو ، ملودی باز,دانلود آهنگ جدید ، دانلود ریمیکس شاد و غمگین ،...,melodybaz.com/%DB%8C%D9%88%D9%86%D8%B3-%D8%A8%...,melodybaz.com,4105
3,غذا و نوشیدنی,بیسکویت یک تغذیه مفید برای کودکان است و میتوان...,طرز تهیه بیسکویت | نحوه تهیه بیسکویت خانگی و ...,طرز تهیه بیسکویت | نحوه تهیه بیسکویت خانگی و ...,طرز تهیه بیسکویت | نحوه تهیه بیسکویت خانگی و ب...,طرز تهیه بیسکویت کره ای برچسب‌ها پیشنهاد نظر ش...,saat24.news/news/388353/%D8%B7%D8%B1%D8%B2-%D8...,saat24.news,2761
4,ورزش,در قرعه کشی لیگ قهرمانان آسیا 2022، 40 باشگاه ...,برنامه قرعه کشی لیگ قهرمانان آسیا ۲۰۲۲+ جدول ب...,برنامه قرعه کشی لیگ قهرمانان آسیا ۲۰۲۲+ جدول,برنامه قرعه کشی لیگ قهرمانان آسیا ۲۰۲۲+ جدول,جزئیات قرعه کشی لیگ قهرمانان آسیا ۲۰۲۲ جزئیات ...,titrebartar.com/fa/news/176194/the-draw-progra...,titrebartar.com,3830
...,...,...,...,...,...,...,...,...,...
10643,کتاب و ادبیات,دانلود رایگان کتاب دنیای پس از مرگ اثر موریس م...,آفتامات |دانلود کتاب دنیای پس از مرگ اثر موری...,آفتامات |دانلود کتاب دنیای پس از مرگ اثر موری...,دانلود کتاب دنیای پس از مرگ اثر موریس مترلینگ,NaN,aftamat.com/document/3419/%D8%AF%D8%A7%D9%86%D...,aftamat.com,20
10644,کتاب و ادبیات,دانلود رمان بامداد خمار از فهیمه رحیمی با لینک...,دانلود رمان بامداد خمار از فهیمه رحیمی دانلود ...,دانلود رمان بامداد خمار از فهیمه رحیمی,دانلود رمان بامداد خمار از فهیمه رحیمی,دانلود آهنگ های محلی و دانلود آهنگ های غمگین ا...,nakaman.ir/82673/%D8%B1%D9%85%D8%A7%D9%86-%D8%...,nakaman.ir,1110
10645,کتاب و ادبیات,این سایت تخصصی برای دانلود کتاب و دانلود مجله ...,دانلود pdf کتاب اطلس تاریخ ایران رایگان Menu ...,دانلود pdf کتاب اطلس تاریخ ایران رایگان,دانلود pdf کتاب اطلس تاریخ ایران رایگان,دانلود pdf دانلود pdf کتاب اطلس تاریخ ایران را...,dehlinks.ir/fa/book/history/book/1178/%D8%AF%D...,dehlinks.ir,2522
10646,کتاب و ادبیات,گلچینی از اشعار عاشقانه و احساسی کوتاه و بلند ...,مجموعه اشعار عاشقانه و زیبای سیمین بهبهانی کوت...,مجموعه اشعار عاشقانه و زیبای سیمین بهبهانی کوت...,مجموعه اشعار عاشقانه و زیبای سیمین بهبهانی کوت...,اشعار زیبای عاشقانه سیمین بهبهانی,ariamag.com/8318/%D8%A7%D8%B4%D8%B9%D8%A7%D8%B...,ariamag.com,3649
10647,کتاب و ادبیات,NaN,دانلود رمان های آوین – دانلود رایگان رمان های ...,دانلود رمان های آوین – دانلود رایگان رمان های ...,دانلود رایگان رمان های ایرانی | نایس بانو,دانلود رمان صرفا جهت اینکه خر فهم شی PDF با لی...,nicbanoo.ir/tag/%D8%AF%D8%A7%D9%86%D9%84%D9%88...,nicbanoo.ir,1947

In [32]:
# function to preprocess the text
normalizer = Normalizer()
stemmer = Stemmer()
stopwords = stopwords_list()

def preprocessing(text):

    # 1. remove punctuation
    text = re.sub(r'[^\w\s]', '', text)

    # 2. normalization
    normalized_text = normalizer.normalize(text)

    # 3. apply stemming
    stemmed_text = ' '.join([stemmer.stem(word) for word in normalized_text.split()])

    # 4. tokenization
    tokens = word_tokenize(stemmed_text)

    # 5. convert to lowercase, remove digits and stopwords
    stopwords = stopwords_list()
    output_tokens = []
    for token in tokens:
        token = token.lower()
        if token.isdigit() or token in stopwords:
            continue
        output_tokens.append(token)

    return output_tokens

In [33]:
# applying the preprocessing function to the 'title' column in both training and test data
X_train = X_train['title'].apply(preprocessing)
X_test = test['title'].apply(preprocessing)

In [34]:
X_train

0        [معرف, دیدن, اسپانیا, کباب, کتاب, خرید, کتاب, ...
1                                      [کباب, برگ, چ, بپز]
2               [دانلود, آهنگ, یونس, بخرد, نا, مه, کافرین]
3              [طرز, بیسکو, بیسکو, خانگ, بیسکو, ساقه, طلا]
4               [برنامه, قرعه‌کش, لیگ, قهرمان, آسیا, جدول]
                               ...
10643      [آفتا, دانلود, کتاب, دنیا, مرگ, موریس, مترلینگ]
10644               [دانلود, ر, بامداد, خمار, فهیمه, رحیم]
10645          [دانلود, pdf, کتاب, اطلس, تاریخ, ایر, رایگ]
10646    [مجموعه, اشعار, عاشقانه, زیبا, سیمین, بهبهان, ...
10647    [دانلود, رمان, آوین, دانلود, رایگ, رمان, ایران...
Name: title, Length: 10648, dtype: object

In [35]:
X_test

4121    [سا, نوب, ده, دک, امیر, داودآباد, فراهان, تخصص...
2005                     [قیم, لپ‌تاپ, اس, آ, امروز, زوم]
4275     [سامانه, شفق, برا, دریاف, وا, قرض‌الحسنه, رونما]
3826    [خرید, کاور, کنترلر, dualsense, ارتش, آب, فروش...
2483                        [معجزه, برا, بیمار, قلب, قرص]
                              ...
3438                    [حک, بازدا, مهاج, پرسپولیس, صادر]
213          [اخبار, شورا, توسعه, فرهنگ, قرآن, صفحه, بیس]
2037                       [متوسطه, دخترانه, نخبگ, بوشهر]
3972    [هورمون, بوس, فروشگاه, اینترنت, گل, گیاه, سبزو...
3566                  [لیس, آموز, نقاش, زرت, ایر, جابینو]
Name: title, Length: 958, dtype: object

In [36]:
# converting the preprocessed 'title' columns from lists to strings and then apply TF-IDF vectorization to both training and test data
tfidf = TfidfVectorizer()

X_train = X_train.apply(lambda x: " ".join(x) if isinstance(x, list) else x)
X_test = X_test.apply(lambda x: " ".join(x) if isinstance(x, list) else x)

X_train = tfidf.fit_transform(X_train)
X_test = tfidf.transform(X_test)

In [37]:
train['category'].unique()

array(['سفر و گردشگری', 'غذا و نوشیدنی', 'موسیقی', 'ورزش', 'خودرو',
       'حقوق و دولت و سیاست', 'تجارت و اقتصاد', 'مد و زیبایی', 'اشتغال',
       'مذهبی', 'هنر و سرگرمی', 'خانواده', 'سلامت', 'مسکن',
       'فیلم و سینما', 'اجتماعی', 'خانه و باغبانی', 'تکنولوژی و کامپبوتر',
       'علم و دانش', 'کتاب و ادبیات', 'حیوانات خانگی', 'تحصیلات'],
      dtype=object)

In [38]:
# encoding the target labels ('y_train') using LabelEncoder to convert them into numeric format
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.transform(test['category'])

In [39]:
# training an SVM model with a linear kernel on the training data
model = SVC(kernel='linear', max_iter=5000)
model.fit(X_train, y_train)

SVC(kernel='linear', max_iter=5000)

In [40]:
# predicting on the train and test sets
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

In [41]:
# model evaluation
score_1 = f1_score(y_train, y_train_pred, average='weighted')
print(f"f1 score on Training Data: {score_1}")

score_2 = f1_score(y_test, y_test_pred, average='weighted')
print(f"f1 score on Training Data: {score_2}")

f1 score on Training Data: 0.9937093657882357
f1 score on Training Data: 0.7356170510993733